CREATE TABLE IF NOT EXISTS public.users (
    email text COLLATE pg_catalog."default",
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    role text COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    active boolean,
    confirmation_otp text COLLATE pg_catalog."default",
    reset_password text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
ALTER TABLE public.users OWNER to postgres;
CREATE TABLE IF NOT EXISTS public.sessions (
    email text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    session_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    valid boolean,
);
-------express-sessions into postgres using connect-pg-simple-------
CREATE TABLE "express_session" (
    "sid" varchar NOT NULL COLLATE "default",
    "sess" json NOT NULL,
    "expire" timestamp(6) NOT NULL
) WITH (OIDS = FALSE);
ALTER TABLE "express_session"
ADD CONSTRAINT "express_session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX "IDX_session_expire" ON "express_session" ("expire");
---------------------------------------------